### ISSUE TITLE
Mirroring repository with colliding/conflicting packages

### ISSUE THREAD

**Issue by joshsouza** [smira/aptly#183]
I am attempting to mirror the following repository:
http://packages.erlang-solutions.com/ubuntu/dists/precise/contrib/binary-amd64/Packages
Unfortunately, after adding the mirror in aptly, updates fail with the following message:
```
Downloading & parsing package files...
Downloading http://packages.erlang-solutions.com/ubuntu/dists/precise/contrib/binary-amd64/Packages.bz2...
ERROR: unable to update: conflict in package elixir_1.0.0-1_all
```
After looking into it, the problem is that the repository itself is broken. If you look at: http://packages.erlang-solutions.com/ubuntu/dists/precise/contrib/binary-amd64/Packages 
and search for 'elixir_' you will find that they have published two separate files (1.0.0-1 and 1.0.2-1) under the same version (1.0.0-1). While this is definitely a mistake on their part, it still prevents me from being able to serve a mirror of this repository using Aptly.
I've looked through the other reported issues, and it appears that if you validly create mirrors and update them, but then go to publish a snapshot/repo/whatever that has this problem, it will not work without the -force-overwrite flag, but the problem here is different in that it's not under my control, and the files aren't conflicting, just the original repository is causing issues.

First off: Is there any way we can get Aptly to intelligently handle this situation? If not, I'll have to go bother the repo owners, and doubt I'll get help there.

Second: If we're going to fix, here is my theory on how to make it work:
1. Allow the download of both files (if they're identical, you wouldn't have to worry about it anyway, as it'd be a duplicate)
2. Alert users to the conflict
3. Allow users to decide upon how to handle the conflict during publishing (which has already been fixed, if I understand it correctly)
4. Alternatively, provide flagging to allow you to specify how to override (newer file timestamp is the only thing I can think of to differentiate)

Let me know if you need any further details!

**Comment by smira** [comment]
@joshsouza unfortunately aptly doesn't support this case (it's broken, more info here http://www.aptly.info/doc/feature/duplicate/). aptly can handle such packages well if they are in different mirrors/snapshots/local repos. I believe `apt` itself might have problems (or unexpected behavior) when working with such repository.

On publishing: it isn't related to force_overwrite, as you have the same package with two different package files, so you can't have it one `Packages` index. You can publish such packages as different components/distributions or under different prefixes (so that they end up in different `Packages` files).

On the possible fix: the only possible fix here (getting aptly architecture into consideration) would be to skip one of the conflicting packages (the one which comes second in the `Packages` index file).

**Comment by smira** [comment]
Fixed in `master, nightly build `aptly_0.9~dev+134+g403c727` released that includes this fix.

**Comment by smira** [comment]
Unfortunately, this mirror is broken in too many ways: it has many missing package files. The only workaround is to filter out such packages.

I've managed to compile filter: `!$Version (1:17.0), !$Version (1:16.b.1)`, but these guys should fix their repo.

**Comment by joshsouza** [comment]
Thanks for the work smira. I agree, these guys are being absolutely nuts about their repo, hopefully I can get them to do something about it, but I'm not holding my breath.
