### ISSUE TITLE
How does aptly manage collisions

### ISSUE THREAD

**Issue by ksalman** [smira/aptly#222]
I am just starting to use aptly and I need to mirror both Debian and Ubuntu repositories. It looks like the directory structure where it puts all the packages is similar, in that it puts all the packages under pool/xx/yy directories, though I don't know how it computes xx and yy.

In any case, if I am mirroring Debian and Ubuntu how does it prevent collisions between files that have the same name between the two repos? Take for example the filename libaa1_1.4p5-43_i386.deb.
```
Debian:
http://mirrors.kernel.org/debian/pool/main/a/aalib/libaa1_1.4p5-43_i386.deb

Ubuntu:
http://mirrors.kernel.org/ubuntu/pool/main/a/aalib/libaa1_1.4p5-43_i386.deb
```

**Comment by smira** [comment]
So, there are two parts of the answer.

First, internal aptly package pool `~/.aptly/pool`: aptly stores all package files (either downloaded from mirrors or imported into local repositories there) under directory `xx/yy`, where `xx` & `yy` are first two bytes of package file MD5. So there's low chance of collision: filenames and first two bytes of MD5 should match. On other hand, if packages files are identical, there would be exactly one copy of file in internal package pool.

Second, package references. If you've got two packages `name_version_arch` with same name, version, arch, they're either identical (same package files) or conflicting. If they're identical - there's no problem. If they're conflicting - aptly handles them internally by appending hash of package files to package key (name, version, arch). Two conflicting packages should never be part of one mirror, local repo, snapshot or published repository. Due to the layout of published repositories, conflicting packages should be published under different prefixes (otherwise they would share one path `~/.aplty/public/pool/main/lib/libaa/...`).

So aptly should handle your case just fine, and it would warn if anything goes wrong :)

**Comment by smira** [comment]
Some more info here: http://www.aptly.info/doc/feature/duplicate/

**Comment by ksalman** [comment]
Ahh.. thanks for the explanation.
