### ISSUE TITLE
no support for -dbgsym packages

### ISSUE THREAD

**Issue by grimmy** [smira/aptly#331]
In stretch, debian added support for dbgsym packages [1].  Here is some sample output.  Packages are built with debuild.

```
aptly repo include -no-remove-files=true -config=../aptly.conf -repo=stretch artifacts
gpgv: Signature made Wed 06 Jan 2016 10:11:54 PM CST using DSA key ID A8AC8032
gpgv: Good signature from "Gary Kramlich (grim) <grim@reaperworld.com>"
Loading repository stretch for changes file gplugin_0.0.21_amd64.changes...
[+] gir1.2-gplugin-0.0_0.0.21_amd64 added
[+] gplugin_0.0.21_source added
[+] libgplugin-dev_0.0.21_amd64 added
[!] libgplugin-gtk-bin-dbgsym_0.0.21_amd64 has been ignored as it doesn't match restriction
[+] libgplugin-gtk-bin_0.0.21_amd64 added
[+] libgplugin-gtk-dev_0.0.21_amd64 added
[+] libgplugin-gtk0-dbg_0.0.21_amd64 added
[+] libgplugin-gtk0_0.0.21_amd64 added
[+] libgplugin-loaders_0.0.21_all added
[!] libgplugin-lua-dbgsym_0.0.21_amd64 has been ignored as it doesn't match restriction
[+] libgplugin-lua_0.0.21_amd64 added
[!] libgplugin-python-dbgsym_0.0.21_amd64 has been ignored as it doesn't match restriction
[+] libgplugin-python_0.0.21_amd64 added
[+] libgplugin0-dbg_0.0.21_amd64 added
[+] libgplugin0_0.0.21_amd64 added
[!] Some files were skipped due to errors:
  artifacts/libgplugin-gtk-bin-dbgsym_0.0.21_amd64.deb
  artifacts/libgplugin-lua-dbgsym_0.0.21_amd64.deb
  artifacts/libgplugin-python-dbgsym_0.0.21_amd64.deb
ERROR: some files failed to be added
```

I've been trying to figure out how the package restrictions work, but so far haven't been able to grok it enough to fix it.

[1] https://wiki.debian.org/AutomaticDebugPackages

**Comment by grimmy** [comment]
forgot to add my aptly version

````
$ apt-cache policy aptly
aptly:
  Installed: 0.9.6~dev+156+g339bf0a
  Candidate: 0.9.6~dev+156+g339bf0a
  Version table:
 *** 0.9.6~dev+156+g339bf0a 500
        500 http://repo.aptly.info nightly/main amd64 Packages
        100 /var/lib/dpkg/status
````

**Comment by smira** [comment]
@grimmy most probably we need some fix here https://github.com/smira/aptly/blob/master/deb/changes.go#L167 

aptly internally tries to make sure that only packages which were built from that `.changes` are processed.

**Comment by grimmy** [comment]
Okay, I was looking at that part, but it wasn't quite clicking on how it worked.  I'll hopefully get a chance to look at it again soon, but I'm not sure when.

**Comment by smira** [comment]
Match is done on `Source: ` field in stanza, so it works usually for all binary packages generated from some source package.

**Comment by smira** [comment]
@grimmy if you could upload .changes file and packages built to some place, it would help me to debug the issue.

**Comment by grimmy** [comment]
@smira here you go
https://guifications.org/jenkins/view/GPlugin/job/gplugin-debian-stretch-amd64/lastSuccessfulBuild/artifact/debian/stretch/artifacts/debs/

**Comment by smira** [comment]
@grimmy sorry for being so slow, but URL doesn't work right now - it gives Proxy Error

**Comment by smira** [comment]
> The only thing I'd change in .changes processing is to add temp dir to aptly config, so it can be on the same filesystem as the rest of the repo. (swap os.TempDir() for some user setting, or default to os.TempDir())
> Then copy with reference/hardlink is possible, and verify the checksums after copy to temp dir. That way all files in temp dir could be safely processed.

I'm ok with custom temp dir (even though I think env variable `TMPDIR` could be used), but I don't think hard-linking makes sense, as it doesn't protect from files being overwritten while being processed (after checksum check).

Let me dig into the reasons behind query filters

**Comment by smira** [comment]
Ah, I remember now why aptly cross-checks `.changes` file and packages. 

This is required to support `uploaders.json` (https://www.aptly.info/doc/aptly/repo/include/) - `.changes` file is checked to comply with `uploaders.json` rules and now package files should match whatever is specified in `.changes`. Otherwise I can prepare `.changes` file which matches something I'm allowed to upload, but instead upload protected package.

**Comment by smira** [comment]
@sobczyk ^

**Comment by sobczyk** [comment]
but you could do it in different order:
1. parse .changes (and verify this files GPG sig)
2. copy it to TempDir
3. verify with uploaders.json (afaik it's atomic, if one package is not allowed the whole .changes is not included)
4. copy all referenced files to TempDir
5. verify all hashes
6. filter Changes.Files by extension (deb, ddeb, udeb, dsc)
7. add filtered to local repository

We can thus omit CollectPackageFiles and PackageQuery, since ordering allows us to.

**Comment by smira** [comment]
> verify with uploaders.json (afaik it's atomic, if one package is not allowed the whole .changes is not included)

`uploaders.json` is applied to `.changes` file (not to packages), as `.changes` file for example might contain local repo name to push new packages to, so we still need to make sure that packages referenced in `.changes` are related to it.

For me the easiest fix would be to add package filter with `<name>-dbgsym` match to the query

**Comment by sobczyk** [comment]
> uploaders.json is applied to .changes file
my mistake, but it holds that uploaders.json allow the .changes and associated files to pass or not (all or nothing)
Point 3 in my example flow takes care of that.

I think, I'll rewrite this tomorrow, it'll be faster than explaining

**Comment by sobczyk** [comment]
OK i get not what you told me about uploaders.json and the PackageQuery,
the user could prepare a fake .changes with packages that do not belong there, and upload what he is not supposed to upload.

Shouldn't then the filtering in ImportPackageFiles reject the whole .changes on premise that some files might be compromised?
Right now it includes packages that match, rejects other

> For me the easiest fix would be to add package filter with <name>-dbgsym match to the query
That's what I've done before, and the problem was that it wasn't matched against fields in changes.

I think I'll implement the easiest solution, that you suggested, match <name>-dbgsym and same source.

The best long term solution would be to allow specifying PckageQuery in uploaders json and scrap the one in the source.
