### ISSUE TITLE
Aptly Publish API should support .(dot) as prefix name

### ISSUE THREAD

**Issue by bhush9** [smira/aptly#339]
In ```PUT /api/publish/:prefix/:distribution``` method if ```prefix``` is dot then it becomes ```PUT /api/publish/:distribution``` which in turn returns the 404. It is impossible to update repositories when prefix is not sub directory.

Relevant log that maybe useful:

```
11:12:21 :get
11:12:21 "/api/publish"
11:12:21 {}
11:12:21 I, [2016-01-28T11:12:21.481071 #15220]  INFO -- : get http://localhost:9090/api/publish
11:12:21 D, [2016-01-28T11:12:21.481151 #15220] DEBUG -- request: User-Agent: "Faraday v0.9.2"
11:12:21 I, [2016-01-28T11:12:21.486074 #15220]  INFO -- Status: 200
11:12:21 D, [2016-01-28T11:12:21.486207 #15220] DEBUG -- response: content-type: "application/json; charset=utf-8"
11:12:21 date: "Thu, 28 Jan 2016 11:12:21 GMT"
11:12:21 content-length: "382"
11:12:21 connection: "close"
11:12:21 :put
11:12:21 "/api/publish/./vivid"
11:12:21 {:body=>"{}"}
11:12:21 I, [2016-01-28T11:12:21.487044 #15220]  INFO -- : put http://localhost:9090/api/publish/vivid
11:12:21 D, [2016-01-28T11:12:21.487125 #15220] DEBUG -- request: User-Agent: "Faraday v0.9.2"
11:12:21 Content-Type: "application/json"
11:12:21 I, [2016-01-28T11:12:21.490014 #15220]  INFO -- Status: 404
11:12:21 D, [2016-01-28T11:12:21.490125 #15220] DEBUG -- response: content-type: "text/plain"
11:12:21 date: "Thu, 28 Jan 2016 11:12:21 GMT"
11:12:21 content-length: "18"
11:12:21 connection: "close"
```

**Comment by philtay** [comment]
This `/api/publish//vivid` (note two slashes after publish) used to work with 0.9.5. Now, with the new version (0.9.6), it doesn't work anymore. The "two slashes" method is documented [here](http://www.aptly.info/doc/api/publish/) (in the relevant example).

This bug broken several of our builds. :( Stick with 0.9.5 for now.

**Comment by apachelogger** [comment]
The problem is that [rfc2396](http://tools.ietf.org/html/rfc2396) defines the paths equal.

- `/api/publish//vivid`
- `/api/publish/./vivid`
- `/api/publish/./././vivid`
- `/api/publish/vivid`

all reference the same absolute path `/api/publish/vivid` as per the RFC. The fact that '/./vivid' could mean anything else is API specific, so this particular bit makes the API non-RFC compliant as it stands right now. For the API to be consistent all of the above paths would have to mean the same thing. Alas, they don't.

Four possible ways of fixing this come to mind:

1. Do server-side URI normalization (i.e. transform the path to its actual absolute version as per the RFC) and then assume that `PUT /api/publish/:distribution` means `PUT /api/publish/./:distribution` and handle it as such. This is fairly convenient from a usage perspective and shouldn't be a problem just so long as there is no actual need to ever PUT only a distribution name.

1. Specify that :prefix must not be '.' and reject normalized `PUT /api/publish/:distribution` as code 400. This essentially enforces the URI normalization requirements on an API level.

1. Change the API to not have :prefix as part of the URI but as query param or in the body. I think this would actually take away elegance from the API.

1. Re-define what :prefix in the URI actually means. Prefix currently is "storage kind (empty for local filesystem, s3 for S3 and swift for Swift)" combined with "publishing prefix, . for root". If local storage actually was 'local' instead of empty, then the URI ambiguity problem goes away because :prefix can no longer be simply a dot. `PUT /api/publish/local:./:distribution` instead of `PUT /api/publish/./:distribution`. This also has the added bonus of unifying the storage handling making for more consistent API overall.

Personally I'd go with that last option. It is most consistent, most expressive and probably makes for cleaner code on both the server and clients.

**Comment by philtay** [comment]
The situation on aptly 0.9.5 is:

* `/api/publish//vivid` works
* `/api/publish/vivid` doesn't work
* `/api/publish/./vivid` doesn't work

On aptly 0.9.6 none of them works.

**Comment by smira** [comment]
I agree with @apachelogger, `//` was a hack that worked temporarily. And we need some explicit prefix like `local:.`

**Comment by smira** [comment]
Actually prefix `:.` should work immediately with aptly, I'm going to try it out.
