### ISSUE TITLE
snapshots and disk usage

### ISSUE THREAD

**Issue by rtennill** [smira/aptly#443]
Is there a way to to see how much disk space is being consumed by snapshots? I have a local Debian mirror that's updated every week or so and I hold onto a handful of recent snapshots 'just in case'. I'm considering using a mirror on a system with much more limited storage so I would like to manage the disk automatically or at least more intelligently.

**Comment by JarenGlover** [comment]
what storage are you using? if in AWS have you saw [EFS](https://aws.amazon.com/efs/)?

**Comment by rtennill** [comment]
The mirror is running on a spare machine in my office at work.

**Comment by smira** [comment]
Snapshot itself is just a list of package references in DB. So it uses few KBs of disk space (depending on snapshot size). 

Snapshot might hold back package files which might otherwise be cleaned up by `aptly db cleanup`. So say you have some package which is referenced only by some snapshot. Files for that package won't be deleted until snapshot is there. If package is referenced in other way (say, it's part of published repository or mirror or ...), snapshot is just reference in DB.

**Comment by rtennill** [comment]
I have been keeping ~ 5 snapshots worth of Debian main/updates/security. It doesn't seem to grow too terribly fast since I only update once or twice a week at most.

Applying a filter to the packages would also recover a lot of storage. Is there some way to use a file to specify the filter instead of generating a huge command line?

**Comment by smira** [comment]
There's no direct support for reading it from file so far

**Comment by rtennill** [comment]
It would be a nice feature to have but certainly near the bottom of the priority list as far as I'm concerned. Should be easy enough to assemble the filter string into an environment variable if the need manifests.
